name: CI
on:
 push:
 pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '15.x'
    - name: Install dependencies  
      run: npm install  
    - name: Linter
      run: npm run lint
    - name: Formatter
      run: npm i -g prettier
    - name: Test
      run: CI=true npm run test
    - name: Build
      run: npm run build

