name: 'Terraform'
on:
    workflow_dispatch:
        inputs:
            environments:
                description: 'Environment to deploy (devel, stage, prod)'
                required: true
                default: 'devel'
jobs:
    terraform:
        name: 'Terraform'
        env:
            ROOTH_PATH: '${{ github.workspace }}/Infra'

        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.environments}}
        defaults:
            run:
                shell: bash
                working-directory: ${{env.ROOTH_PATH}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: 'Setup_terraform'
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.7.5
            - name: 'Terraform init'
              working-directory: ${{env.ROOTH_PATH}}
              run: terraform init
            - name: 'set workspace'
              working-directory: ${{env.ROOTH_PATH}}
              run: |
               terraform workspace select ${{ github.event.inputs.environment}} || terraform workspace new ${{ github.event.inputs.environment}} 
            - name: 'Terraform plan'
              working-directory: ${{env.ROOTH_PATH}}
              run: terraform plan --var-file ${{ github.event.inputs.environment }}.tfvars
            - name: 'Terraform apply'
              working-directory: ${{env.ROOTH_PATH}}
              run: terraform apply --var-file ${{ github.event.inputs.environment }}.tfvars -auto-approve
